--일반게임 판매 매출 확인
SELECT SUM(T2.S_PROFIT - T1.G_SUPPLY_PRICE) AS PROFIT_S
FROM GAMES_TBL T1, SALES_TBL T2
WHERE T1.G_ID = T2.G_ID
;

--예약게임 판매 매출 확인
SELECT SUM(T2.A_PROFIT - T1.G_SUPPLY_PRICE) AS PROFIT_A
FROM GAMES_TBL T1, SALE_APPLYS_TBL T2
WHERE T1.G_ID = T2.G_ID
;

--순 이익 구하기
SELECT '갬성게임즈' AS PLATFORM ,PROFIT_S + PROFIT_A AS N_PROFIT
FROM
(
SELECT SUM(T2.S_PROFIT - T1.G_SUPPLY_PRICE) AS PROFIT_S
FROM GAMES_TBL T1, SALES_TBL T2
WHERE T1.G_ID = T2.G_ID
) T1,(
SELECT SUM(T2.A_PROFIT - T1.G_SUPPLY_PRICE) AS PROFIT_A
FROM GAMES_TBL T1, SALE_APPLYS_TBL T2
WHERE T1.G_ID = T2.G_ID
) T2
;

--고객별 일반게임 판매 매출
SELECT T1.CT_NAME, NVL(T2.PROFIT_S,0) AS SALES, RANK() OVER(ORDER BY NVL(T2.PROFIT_S,0) DESC) AS RANK
FROM CUSTOMERS_TBL T1,
(
SELECT CT_ID, SUM(S_PROFIT) AS PROFIT_S
FROM SALES_TBL
GROUP BY CT_ID
) T2
WHERE T1.CT_ID = T2.CT_ID(+)
ORDER BY RANK() OVER(ORDER BY NVL(T2.PROFIT_S,0) DESC)
;


--고객별 순이익 
SELECT T1.CT_NAME, NVL(T2.PROFIT_S,0) AS SALES, RANK() OVER(ORDER BY NVL(T2.PROFIT_S,0) DESC) AS RANK
FROM CUSTOMERS_TBL T1,
(
SELECT T1.CT_ID, SUM(T1.S_PROFIT - T2.G_SUPPLY_PRICE) AS PROFIT_S
FROM SALES_TBL T1, GAMES_TBL T2
WHERE T1.G_ID = T2.G_ID
GROUP BY T1.CT_ID
) T2
WHERE T1.CT_ID = T2.CT_ID(+)
ORDER BY RANK() OVER(ORDER BY NVL(T2.PROFIT_S,0) DESC)
;


--고객별 예약게임 판매매출
SELECT T1.CT_NAME, NVL(T2.PROFIT_A,0) AS SALES, RANK() OVER(ORDER BY NVL(T2.PROFIT_A,0) DESC) AS RANK
FROM CUSTOMERS_TBL T1,
(
SELECT CT_ID, SUM(A_PROFIT) AS PROFIT_A
FROM SALE_APPLYS_TBL
GROUP BY CT_ID
) T2
WHERE T1.CT_ID = T2.CT_ID(+)
ORDER BY RANK() OVER(ORDER BY NVL(T2.PROFIT_A,0) DESC)
;

-- 고객별 예약게임 순이익
SELECT T1.CT_NAME, NVL(T2.PROFIT_A,0) AS SALES, RANK() OVER(ORDER BY NVL(T2.PROFIT_A,0) DESC) AS RANK
FROM CUSTOMERS_TBL T1,
(
SELECT T1.CT_ID, SUM(T1.A_PROFIT - T2.G_R_SUPPLY_PRICE) AS PROFIT_A
FROM SALE_APPLYS_TBL T1, RESERVATION_GAMES_TBL T2
WHERE T1.G_ID = T2.G_ID
GROUP BY T1.CT_ID
) T2
WHERE T1.CT_ID = T2.CT_ID(+)
ORDER BY RANK() OVER(ORDER BY NVL(T2.PROFIT_A,0) DESC)
;

--고객별 총 매출 구하기
SELECT T1.CT_NAME, NVL(T2.PROFIT_S,0) + NVL(T3.PROFIT_A,0) AS SALES, 
RANK() OVER(ORDER BY NVL(T2.PROFIT_S,0) + NVL(T3.PROFIT_A,0) DESC) AS RANK
FROM CUSTOMERS_TBL T1,
(
SELECT CT_ID, SUM(S_PROFIT) AS PROFIT_S
FROM SALES_TBL
GROUP BY CT_ID
) T2,(
SELECT CT_ID, SUM(A_PROFIT) AS PROFIT_A
FROM SALE_APPLYS_TBL
GROUP BY CT_ID
) T3
WHERE T1.CT_ID = T2.CT_ID(+)
AND T1.CT_ID = T3.CT_ID(+)
ORDER BY RANK() OVER(ORDER BY NVL(T2.PROFIT_S,0) + NVL(T3.PROFIT_A,0) DESC)
;

--고객별 총 순이익 구하기
SELECT T1.CT_NAME, NVL(T2.PROFIT_S,0) + NVL(T3.PROFIT_A,0) AS SALES, 
RANK() OVER(ORDER BY NVL(T2.PROFIT_S,0) + NVL(T3.PROFIT_A,0) DESC) AS RANK
FROM CUSTOMERS_TBL T1,
(
SELECT T1.CT_ID, SUM(T1.S_PROFIT - T2.G_SUPPLY_PRICE) AS PROFIT_S
FROM SALES_TBL T1, GAMES_TBL T2
WHERE T1.G_ID = T2.G_ID
GROUP BY T1.CT_ID
) T2,(
SELECT T1.CT_ID, SUM(T1.A_PROFIT - T2.G_R_SUPPLY_PRICE) AS PROFIT_A
FROM SALE_APPLYS_TBL T1, RESERVATION_GAMES_TBL T2
WHERE T1.G_ID = T2.G_ID
GROUP BY T1.CT_ID
) T3
WHERE T1.CT_ID = T2.CT_ID(+)
AND T1.CT_ID = T3.CT_ID(+)
ORDER BY RANK() OVER(ORDER BY NVL(T2.PROFIT_S,0) + NVL(T3.PROFIT_A,0) DESC)
;

--국가별 일반게임 판매 매출액

SELECT CMS_NAME, SALES, RANK() OVER(ORDER BY NVL(SALES,0) DESC) AS RANK
FROM (
SELECT DECODE(T3.CMS_NAME,NULL,'합계',T3.CMS_NAME) AS CMS_NAME, SUM(NVL(T2.S_PROFIT,0)) AS SALES
FROM CUSTOMERS_TBL T1, SALES_TBL T2 , COMMONS_TBL T3
WHERE T1.CT_ID = T2.CT_ID(+)
AND T1.CT_REGION(+) = T3.CMS_ID
AND T3.PARENT_CMS_ID = 'CMS003'
GROUP BY ROLLUP (T3.CMS_NAME)
)
;

--국가별 예약게임 판매 매출액
SELECT CMS_NAME, SALES, RANK() OVER(ORDER BY NVL(SALES,0) DESC) AS RANK
FROM (
SELECT T3.CMS_NAME, SUM(NVL(T2.A_PROFIT,0)) AS SALES
FROM CUSTOMERS_TBL T1, SALE_APPLYS_TBL T2 , COMMONS_TBL T3
WHERE T1.CT_ID = T2.CT_ID(+)
AND T1.CT_REGION(+) = T3.CMS_ID
AND T3.PARENT_CMS_ID = 'CMS003'
GROUP BY T3.CMS_ID, T3.CMS_NAME
)
;

--국가별 총 핀매 매출액
SELECT T1.CMS_NAME, NVL(T2.SALES_S,0) + NVL(T3.SALES_A,0) AS SALES, 
RANK() OVER(ORDER BY NVL(T2.SALES_S,0) + NVL(T3.SALES_A,0) DESC) AS RANK
FROM COMMONS_TBL T1,
(
SELECT T3.CMS_ID, SUM(NVL(T2.S_PROFIT,0)) AS SALES_S
FROM CUSTOMERS_TBL T1, SALES_TBL T2 , COMMONS_TBL T3
WHERE T1.CT_ID = T2.CT_ID
AND T1.CT_REGION = T3.CMS_ID
GROUP BY T3.CMS_ID
) T2, (
    SELECT T3.CMS_ID, SUM(NVL(T2.A_PROFIT,0)) AS SALES_A
    FROM CUSTOMERS_TBL T1, SALE_APPLYS_TBL T2 , COMMONS_TBL T3
    WHERE T1.CT_ID = T2.CT_ID
    AND T1.CT_REGION = T3.CMS_ID
    GROUP BY T3.CMS_ID
) T3
WHERE T1.CMS_ID = T2.CMS_ID(+)
AND T1.CMS_ID = T3.CMS_ID(+)
AND T1.PARENT_CMS_ID = 'CMS003'
ORDER BY RANK() OVER(ORDER BY NVL(T2.SALES_S,0) + NVL(T3.SALES_A,0) DESC)
;

--장르별 일반게임 판매매출 확인
SELECT CMS_NAME, SALES, RANK() OVER(ORDER BY SALES DESC) AS RANK
FROM(
SELECT T2.CMS_NAME, SUM(NVL(T3.S_PROFIT,0)) AS SALES
FROM GAMES_TBL T1, COMMONS_TBL T2, SALES_TBL T3
WHERE T1.G_GENRE(+) = T2.CMS_ID
AND T1.G_ID = T3.G_ID(+)
AND T2.PARENT_CMS_ID = 'CMS004'
GROUP BY T2.CMS_NAME
)
ORDER BY RANK() OVER(ORDER BY SALES DESC)
;

--장르별 예약게임 판매 확인
SELECT CMS_NAME, SALES, RANK() OVER(ORDER BY SALES DESC) AS RANK
FROM(
SELECT T2.CMS_NAME, SUM(NVL(T3.A_PROFIT,0)) AS SALES
FROM GAMES_TBL T1, COMMONS_TBL T2, SALE_APPLYS_TBL T3
WHERE T1.G_GENRE(+) = T2.CMS_ID
AND T1.G_ID = T3.G_ID(+)
AND T2.PARENT_CMS_ID = 'CMS004'
GROUP BY T2.CMS_NAME
)
ORDER BY RANK() OVER(ORDER BY SALES DESC)
;

--장르별 총 판매 확인
SELECT T1.CMS_NAME, SALES_S + SALES_A AS SALES, RANK() OVER(ORDER BY SALES_S + SALES_A DESC) AS RNAK
FROM
(
SELECT T2.CMS_ID, T2.CMS_NAME, SUM(NVL(T3.S_PROFIT,0)) AS SALES_S
FROM GAMES_TBL T1, COMMONS_TBL T2, SALES_TBL T3
WHERE T1.G_GENRE(+) = T2.CMS_ID
AND T1.G_ID = T3.G_ID(+)
AND T2.PARENT_CMS_ID = 'CMS004'
GROUP BY T2.CMS_ID, T2.CMS_NAME
) T1,
(
SELECT T2.CMS_ID, T2.CMS_NAME, SUM(NVL(T3.A_PROFIT,0)) AS SALES_A
FROM GAMES_TBL T1, COMMONS_TBL T2, SALE_APPLYS_TBL T3
WHERE T1.G_GENRE(+) = T2.CMS_ID
AND T1.G_ID = T3.G_ID(+)
AND T2.PARENT_CMS_ID = 'CMS004'
GROUP BY T2.CMS_ID, T2.CMS_NAME
) T2
WHERE T1.CMS_ID = T2.CMS_ID
ORDER BY RANK() OVER(ORDER BY SALES_S + SALES_A DESC)
;