create or replace NONEDITIONABLE FUNCTION FUNC_SALES_INSERT_PT_ID RETURN VARCHAR2 
AS 
        
        FUNC_PT_ID          CHAR(5);

BEGIN

        SELECT 'PT' || TO_CHAR(TO_NUMBER(SUBSTR(MAX(PT_ID), 3)) + 1, 'FM000')
        INTO FUNC_PT_ID
        FROM POINT_TBL
        ;

  RETURN FUNC_PT_ID;
END FUNC_SALES_INSERT_PT_ID;