SELECT * FROM PROFESSORS
WHERE PID = 'P001'
;

SELECT * FROM EXAMS
WHERE PID = 'P001'
;

--PL SQL
--TRANSACT SQL --> T SQL

SELECT T1.PNAME, T2.ENAME 
FROM PROFESSORS T1, EXAMS T2
WHERE T1.PID = T2.PID
AND T1.PID = 'P001'
;

SELECT *
FROM SUBJECTS
;

SELECT T1.SNAME, T2.ENAME 
FROM SUBJECTS T1, EXAMS T2
WHERE T1.SUBID = T2.SUBID
AND T1.SUBID = 'SUB1'
;

INSERT INTO EXAMS VALUES('P001','SUB6', 'À½¾Ç½ÃÇè ¸Þ·Õ');

--COMMIT;

UPDATE SUBJECTS
SET SUBID = 'SUB' || SUBSTR(SUBID,4,1)
;

UPDATE EXAMS
SET SUBID = 'SUB' || SUBSTR(SUBID,4,1)
;