--학과테이블
CREATE TABLE PARTS
(
    PARTID CHAR(4) NOT NULL PRIMARY KEY,
    PARTNAME VARCHAR2(30) NOT NULL,
    PARTCONTENT VARCHAR2(200) NULL
);

INSERT INTO PARTS VALUES('PT01','컴퓨터공학', NULL);
INSERT INTO PARTS VALUES('PT02','영어영문', NULL);
INSERT INTO PARTS VALUES('PT03','산업공학', NULL);

SELECT * FROM PARTS;

--COMMIT;

UPDATE STUDENTS
SET SPART = 'PT01'
WHERE SPART = '컴퓨터공학'
;

UPDATE STUDENTS
SET SPART = 'PT02'
WHERE SPART = '영어영문'
;

UPDATE STUDENTS
SET SPART = 'PT03'
WHERE SPART = '수학과' OR SPART = '물리학과'
;

--ROLLBACK;
--COMMIT;

SELECT T1.SNAME, T1.SGENDER, T1.STEL, T1.SADDR, T1.SHOBBY, T2.PARTNAME
FROM STUDENTS T1, PARTS T2
WHERE T1.SPART  = T2.PARTID
;
INSERT INTO STUDENTS VALUES('S00003', '전우치', '25', 'M', '0105414', '창원', '게임', 'PT01');
INSERT INTO STUDENTS VALUES('S00004', '김갑순', '23', 'F', '0105478', '창원', '축구', 'PT01');
--COMMIT;

SELECT * FROM STUDENTS;
SELECT * FROM ATTENDANCE;

--학생별 출석횟수

SELECT T1.SID, T1.SNAME, COUNT(SNAME)
FROM STUDENTS T1, ATTENDANCE T2
WHERE T1.SID = T2.SID
GROUP BY T1.SID, T1.SNAME
;
--OUTER JOIN
--1.LEFT OUTER JOIN
--2.RIGHT OUTER JOIN
SELECT *
FROM STUDENTS T1, ATTENDANCE T2, ATTENDANCE T3
WHERE T1.SID = T2.SID(+)
AND T2.SID IS NULL
;