SELECT * FROM DR_MEMBER_TBL;
SELECT * FROM DRIVERS_TBL;
SELECT * FROM RESERVATION_TBL;
SELECT * FROM FINISH_DRIVE_TBL;
SELECT * FROM DRIVER_RST_TBL;

--1. 대리기사중에 콜을 안잡은 사람

SELECT * 
FROM DRIVERS_TBL T1, DRIVER_RST_TBL T2
WHERE T1.DR_ID = T2.DR_ID(+)
AND T2.DR_ID IS NULL
;

--2. 예약들중에 콜이 잡히지 않고 자연스럽게 취소되버린 사람들

SELECT *
FROM RESERVATION_TBL T1, DRIVER_RST_TBL T2
WHERE T1.R_ID = T2.R_ID(+)
AND T2.R_ID IS NULL
;

--3. 3만원 예약을 마무리한 기사

SELECT * FROM DRIVERS_TBL;
SELECT * FROM RESERVATION_TBL;
SELECT * FROM DRIVER_RST_TBL;

--대리기사별 콜 숫자 리스트
SELECT T1.DR_ID, T1.DR_NAME, COUNT(T2.DR_ID) AS CNT
FROM DRIVERS_TBL T1, DRIVER_RST_TBL T2
WHERE T1.DR_ID = T2.DR_ID(+)
GROUP BY T1.DR_ID, T1.DR_NAME
;

--3만원이상 예약한 대리기사 이름
SELECT *
FROM DRIVERS_TBL T1, RESERVATION_TBL T2, DRIVER_RST_TBL T3
WHERE T1.DR_ID = T3.DR_ID
AND T2.R_ID = T3.R_ID
AND T2.R_PAY >= 30000
;

--3만원이상 대리가 콜이 되지 않은 예약
SELECT *
FROM DRIVERS_TBL T1, RESERVATION_TBL T2, DRIVER_RST_TBL T3
WHERE T1.DR_ID = T3.DR_ID(+)
AND T2.R_ID = T3.R_ID(+)
--AND T1.DR_NAME IS NULL
--AND T2.R_PAY >= 30000
;

SELECT *
FROM DRIVERS_TBL T1, DRIVER_RST_TBL T3, RESERVATION_TBL T2
WHERE T1.DR_ID = T3.DR_ID(+)
AND T2.R_ID = T3.R_ID(+)
;