CREATE TABLE PRODUCTS
(
    PID CHAR(4) NOT NULL, --상품아이디
    PNAME VARCHAR2(40)  NOT NULL --상품명
);

INSERT INTO PRODUCTS(PID, PNAME) VALUES('P001', '마이구미');
INSERT INTO PRODUCTS(PID, PNAME) VALUES('P002', '조리퐁');
INSERT INTO PRODUCTS(PID, PNAME) VALUES('P003', '새우깡');
INSERT INTO PRODUCTS(PID, PNAME) VALUES('P004', '맛짱');

--insert와 update는 rollback, commit를 가지고있다

SELECT *
FROM PRODUCTS
WHERE PNAME = '새우깡' OR PID = 'P004'
;

SELECT *
FROM PRODUCTS
WHERE PNAME = '새우깡' AND PID = 'P003'
;

--ROLLBACK;
--COMMIT;