--회원테이블
CREATE TABLE MEMBERS
(
    MID CHAR(4) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    ETC VARCHAR2(500) NULL
);

INSERT INTO MEMBERS(MID, MNAME, ETC) VALUES('M001', '홍길동', '잘생겼음');
INSERT INTO MEMBERS(MID, MNAME, ETC) VALUES('M002', '김갑돌');
INSERT INTO MEMBERS(MID, MNAME, ETC) VALUES('M003', '김갑순', '');
INSERT INTO MEMBERS(MID, MNAME, ETC) VALUES('M004', '박칠도', '키가 매우 큼');
INSERT INTO MEMBERS(MID, MNAME, ETC) VALUES('M005', '홍길동', '     ');

SELECT * FROM MEMBERS;

--1. ETC가 비어있는 ROW를 가져오자
SELECT * FROM MEMBERS
WHERE ETC IS NULL
;

--2. 정렬
SELECT MID, MNAME FROM MEMBERS
WHERE ETC IS NULL
ORDER BY MNAME ASC --오름차순
;

SELECT * FROM MEMBERS
WHERE (MID = 'M001' OR MID = 'M002') AND MNAME = '홍길동'
;


--NULL - 참조값 없음

--ROLLBACK;
--COMMIT;