CREATE TABLE STUDENTS
(
    SID CHAR(4) NOT NULL,
    SNAME VARCHAR(30) NOT NULL,
    AGE NUMBER(3) NOT NULL,
    AVG NUMBER(5,2) NOT NULL,
    ETC VARCHAR(300)
);

ALTER TABLE STUDENTS MODIFY SID CHAR(4);

--ROLLBACK;
--COMMIT;

INSERT INTO STUDENTS(SID, SNAME, AGE, AVG) VALUES('S001', 'È«±æµ¿', 20, 70.74);
INSERT INTO STUDENTS(SID, SNAME, AGE, AVG) VALUES('S002', 'Àü¿ìÄ¡', 80, 80);
INSERT INTO STUDENTS(SID, SNAME, AGE, AVG) VALUES('S003', '±è°©µ¹', 58, 100);
INSERT INTO STUDENTS(SID, SNAME, AGE, AVG) VALUES('S004', '±è°©¼ø', 34, 55.78);
INSERT INTO STUDENTS(SID, SNAME, AGE, AVG) VALUES('S005', '¼ºÃáÇâ', 19, 15.9);
INSERT INTO STUDENTS(SID, SNAME, AGE, AVG) VALUES('S006', '¼ºÃáÇâ', 80, 76.5);
INSERT INTO STUDENTS(SID, SNAME, AGE, AVG) VALUES('S007', '¼ºÃáÇâ', 35, 55.55);
INSERT INTO STUDENTS(SID, SNAME, AGE, AVG) VALUES('S008', '¼ºÃáÇâ', 50, 34.78);

SELECT *
FROM STUDENTS
;

SELECT SNAME, AGE
FROM STUDENTS
WHERE ETC IS NULL
;

UPDATE STUDENTS
SET ETC = '³ª´Â È«±æµ¿ÀÌ´Ù'
WHERE SID = 'S001'
;

UPDATE STUDENTS
SET ETC = '³ª´Â Àü¿ìÄ¡´Ù'
WHERE SID = 'S002'
;

UPDATE STUDENTS
SET AGE = AGE + 1
;

UPDATE STUDENTS
SET SNAME = '°©µ¹ÀÌ'||'°©¼øÀÌ'
WHERE SNAME LIKE '%¼ø'
;

UPDATE STUDENTS
SET SID = SID || '1'
; -- ¿À·ù

UPDATE STUDENTS
SET AVG = AVG + 10000
;--²Ë Ã¤¿öÁ®¼­ ¾ÈµÊ

DELETE FROM STUDENTS
WHERE SID = 'S007'
;

SELECT SID,SNAME,AVG 
FROM STUDENTS
WHERE (AGE > 30 AND SNAME LIKE '%°©%') OR SNAME IN '¼º'||'ÃáÇâ' AND AVG > 34.78
ORDER BY SNAME DESC
;