--data type
--문자열, 숫자열, LOB
CREATE TABLE STUDENTS
(
    SID CHAR(6) NOT NULL,
    SNAME VARCHAR2(30) NOT NULL
);

--CHAR : 무조건 6자리  6BYTE DATA를 입력하겠다고 확신

SELECT LENGTH(SID), SID, LENGTHB(SNAME)
FROM STUDENTS;

INSERT INTO STUDENTS(SID, SNAME) VALUES('S00002','전우치');
INSERT INTO STUDENTS(SID, SNAME) VALUES('S00003','가나다라마');
INSERT INTO STUDENTS(SID, SNAME) VALUES('S00004','가나다라마바사아자차');
INSERT INTO STUDENTS(SID, SNAME) VALUES('S00005','가나다라마바사아자차1');

SELECT * FROM STUDENTS;

--COMMIT;
--ROLLBACK;

SELECT * FROM STUDENTS
WHERE TRIM(SID) = 'S001';

--홍길동 나이 UPDATE 32
UPDATE STUDENTS
SET AGE = 32
WHERE SID = 'S001  ';

UPDATE STUDENTS
SET AGE = 999
WHERE SID = 'S00002  ';