CREATE TABLE SCORES
(
    SUBJECT_ID  CHAR(6) NOT NULL,
    SUBJECT_NAME VARCHAR2(30) NOT NULL,
    SCORE NUMBER(5,2) NOT NULL
);

--DROP TABLE SCORES;

INSERT INTO SCORES(SUBJECT_ID, SUBJECT_NAME, SCORE) VALUES('S00001', '국어', 87);
INSERT INTO SCORES(SUBJECT_ID, SUBJECT_NAME, SCORE) VALUES('S00002', '수학', 97);
INSERT INTO SCORES(SUBJECT_ID, SUBJECT_NAME, SCORE) VALUES('S00003', '영어', 76);
INSERT INTO SCORES(SUBJECT_ID, SUBJECT_NAME, SCORE) VALUES('S00004', '국어', 0004);
INSERT INTO SCORES(SUBJECT_ID, SUBJECT_NAME, SCORE) VALUES('S00005', '영어', 77.74);
INSERT INTO SCORES(SUBJECT_ID, SUBJECT_NAME, SCORE) VALUES('S00006', '영어', 77.45);
INSERT INTO SCORES(SUBJECT_ID, SUBJECT_NAME, SCORE) VALUES('S00007', '영어', 100);
INSERT INTO SCORES(SUBJECT_ID, SUBJECT_NAME, SCORE) VALUES('S00008', '영어', 83.007);

SELECT * FROM SCORES;

--COMMIT;