SELECT * FROM STUDENTS;

-- 1. 25살 이상이고 부산에사는 학생들

SELECT * 
FROM STUDENTS
WHERE SAGE >= 25 AND SADDR = '부산'
;

-- 2. 부산에 사는데 김씨성을 가진 학생들

SELECT *
FROM STUDENTS
WHERE SADDR IN '부산' AND SNAME LIKE '김%'
;

-- 3. 부산에 사는데 전화번호 끝자리가 '4444'로 끝나는 학생들

SELECT *
FROM STUDENTS
WHERE SADDR = '부산' AND STEL LIKE '%4444'
;

-- 지역별, 나이별, 출신별,....
-- GROUP을 만든다

-- 집계함수 - 내장함수 (오라클이 기본적으로 지원하는 함수)
-- 1. 데이터 개수를 센다
--      COUNT()
-- 2. 데이터의 합계를 구한다
--      SUM()
-- 3. 데이터의 평균을 구한다
--      AVG()
-- 4. MAX()
-- 5. MIN()

-- 현재 STUDENTS 테이블의 총 ROW수가 몇개지

SELECT COUNT(*) FROM STUDENTS;

SELECT COUNT(SNAME) FROM STUDENTS
WHERE SADDR = '부산'
;

-- 현재 STUDENTS 테이블에 등록되어 있는 학생들의 평균나이가 어떻게 될까

SELECT AVG(SAGE) FROM STUDENTS
WHERE SADDR = '부산'
;

SELECT SUM(SAGE) FROM STUDENTS
;

SELECT COUNT(*), AVG(SAGE), SUM(SAGE) FROM STUDENTS;
--그룹함수는 그룹함수만 표시된다 데이터는 ROW이기 때문에

-- GROUP

SELECT SADDR, COUNT(*) FROM STUDENTS
--WHERE SADDR = '부산'
GROUP BY SADDR
;

-- 지역별 평균나이를 보여주세요 - 25살 보다 많은 지역

SELECT * FROM
(
SELECT SADDR, AVG(SAGE) AS AV
FROM STUDENTS
GROUP BY SADDR
)
WHERE AV > 25
;

SELECT SADDR, AVG(SAGE)
FROM STUDENTS
GROUP BY SADDR
;

-- 4. 남성, 여성 몇명??

SELECT SGENDER, COUNT(*) 
FROM STUDENTS
GROUP BY SGENDER
;

SELECT * 
FROM STUDENTS
;

-- 지역별, 성별 숫자

SELECT SADDR, SGENDER, COUNT(*)
FROM STUDENTS
GROUP BY SADDR, SGENDER
ORDER BY SADDR ASC
;

SELECT * FROM PROFESSORS;

SELECT MIN(BIRTH) FROM PROFESSORS;

SELECT MIN(SAGE) FROM STUDENTS;

--문자열 자르기

SELECT SUBSTR(BIRTH, 1, 4)
FROM PROFESSORS
;

-- 1. 1980년도 태생 교수를 찾자

SELECT *
FROM PROFESSORS
WHERE SUBSTR(BIRTH, 1,4) >= 1980
;

SELECT *
FROM PROFESSORS
WHERE BIRTH LIKE '198%'
;

-- 2. 1970 : 몇명 1980 : 몇명,
SELECT SUBSTR(BIRTH,1,3) || '0', COUNT(*) 
FROM PROFESSORS
GROUP BY SUBSTR(BIRTH,1,3);

SELECT SUBSTR(BIRTH, 1, 4), COUNT(*)
FROM PROFESSORS
GROUP BY SUBSTR(BIRTH, 1, 4)
ORDER BY SUBSTR(BIRTH, 1, 4) ASC
;

SELECT SUBSTR(BIRTH, 1, 4), COUNT(*)
FROM PROFESSORS
WHERE SUBSTR(BIRTH, 1, 4) = '1980'
GROUP BY SUBSTR(BIRTH, 1, 4)
;