CREATE TABLE PRODUCTS
(
    PROID CHAR(6) NOT NULL PRIMARY KEY,
    PRONAME VARCHAR2(30) NOT NULL,
    PROCONT VARCHAR2(200) NOT NULL
);

INSERT INTO PRODUCTS VALUES('PRO01', '키보드', '소희가 가지고 있는 비싼 키보드');
INSERT INTO PRODUCTS VALUES('PRO02', '마우스', '동욱이가 가지고 있는 하빠리 마우스');
INSERT INTO PRODUCTS VALUES('PRO03', '스피커', '정은이꺼');

SELECT * FROM PRODUCTS;
SELECT * FROM PURCHASES;
--COMMIT;

-- INLINE VIEW
SELECT T3.MNAME, T1.PRONAME, T2.PRICE, T2.QTY
FROM PRODUCTS T1, PURCHASES T2, MEMBERS T3
WHERE T1.PROID = T2.PROID
AND T2.MID = T3.MID
;

--박경숙 고객이 구매한 총가격 -- 박경숙 30000
SELECT T1.MID, T1.MNAME, SUM(T2.PRICE * QTY)
FROM MEMBERS T1, PURCHASES T2
WHERE T1.MID = T2.MID
GROUP BY T1.MID, T1.MNAME
;

SELECT * FROM STUDENTS;

--DATA의 무결성
CREATE TABLE PARTS
