SELECT * FROM STUDENTS;

SELECT * FROM ATTENDANCE;

INSERT INTO ATTENDANCE VALUES(30,'S00003', '20210403', '08:50', NULL);
--COMMIT;

SELECT *
FROM STUDENTS T1, ATTENDANCE T2
WHERE T1.SID = T2.SID(+)
AND ATTID IS NULL
;

--4월 2일날 출석을 하지 않은 학생

SELECT * FROM
STUDENTS T1,
(
    SELECT * FROM ATTENDANCE
    WHERE ADATE = '20210402'
) T2
WHERE T1.SID = T2.SID(+)
AND T2.SID IS NULL
;

--날짜별로 몇명 출석했는지 알아보자

SELECT ADATE, COUNT(*)
FROM STUDENTS T1, ATTENDANCE T2
WHERE T1.SID = T2.SID
GROUP BY ADATE
;

--날짜별로 결석한 학생 숫자
SELECT * FROM
STUDENTS T1,
(
    SELECT * FROM ATTENDANCE
    WHERE ADATE = '20210402'
) T2,
(
    SELECT * FROM ATTENDANCE
    WHERE ADATE = '20210403'
) T3,
(
    SELECT * FROM ATTENDANCE
    WHERE ADATE = '20210401'
) T4
WHERE T1.SID = T2.SID(+)
AND T1.SID = T3.SID(+)
AND T1.SID = T4.SID(+)
--AND (T2.SID IS NULL
--OR T3.SID IS NULL
--OR T4.SID IS NULL)
;

SELECT ADATE, (SELECT COUNT(*) FROM STUDENTS)- COUNT(*)
FROM ATTENDANCE
GROUP BY ADATE
;

SELECT T3.ADATE, T2.SNAME, COUNT(*)
FROM ATTENDANCE T1, STUDENTS T2,
(
SELECT ADATE
FROM ATTENDANCE
GROUP BY ADATE
) T3
WHERE T1.SID(+) = T2.SID
AND T1.ADATE(+) = T3.ADATE
AND T1.SID IS NULL
GROUP BY T3.ADATE, T2.SNAME
ORDER BY T3.ADATE
;
SELECT *
FROM ATTENDANCE T1, STUDENTS T2,
(
SELECT ADATE
FROM ATTENDANCE
GROUP BY ADATE
) T3
WHERE T1.SID(+) = T2.SID
AND T1.ADATE(+) = T3.ADATE
--AND T1.SID IS NULL
--GROUP BY T3.ADATE, T2.SNAME
--ORDER BY T3.ADATE
;
SELECT * FROM STUDENTS;
SELECT * FROM ATTENDANCE;

