SELECT * FROM DR_MEMBER_TBL;
SELECT * FROM DRIVERS_TBL;
SELECT * FROM RESERVATION_TBL;
SELECT * FROM FINISH_DRIVE_TBL;
SELECT * FROM DRIVER_RST_TBL;

SELECT * FROM RESERVATION_TBL
WHERE R_PAY = (SELECT MAX(R_PAY) FROM RESERVATION_TBL)
;

SELECT * FROM RESERVATION_TBL
WHERE R_STR IN ('부경대앞', '동의대앞')
;
--IN은 OR와 같다

-- 30000원 이상의 예약을 마무리한 기사
SELECT * FROM DRIVERS_TBL;
SELECT * FROM DRIVER_RST_TBL;
SELECT * FROM RESERVATION_TBL;

SELECT *
FROM DRIVERS_TBL T1, DRIVER_RST_TBL T2, RESERVATION_TBL T3
WHERE T1.DR_ID(+) = T2.DR_ID
AND T2.R_ID(+) = T3.R_ID
AND T3.R_PAY >= 30000
;

SELECT * FROM RESERVATION_TBL
WHERE R_PAY >= 30000
;