-- TRUNC - TRUNCATE
-- ROUND
-- 수학적
SELECT ROUND(13.577, 2) FROM DUAL; -- 둘째값을 올림
SELECT TRUNC(13.577, 2) FROM DUAL; -- 둘째값을 버림

--날짜
SELECT TO_CHAR(TRUNC(SYSDATE), 'YYYY-MM-DD HH24:MI:SS')FROM DUAL;

CREATE TABLE IMSI
(
    DATE1 DATE NOT NULL,
    DATE2 DATE NOT NULL
);

INSERT INTO IMSI VALUES(
    TO_DATE('2021-04-14 11:14:33', 'YYYY-MM-DD HH:MI:SS'),
    TO_DATE('2021-01-19 05:22:55', 'YYYY-MM-DD HH:MI:SS')
);

SELECT * FROM IMSI;
--COMMIT;

--시분초 때문에 날짜계산이 애매할때
SELECT TRUNC(DATE1) - TRUNC(DATE2), TRUNC(DATE1), TRUNC(DATE2) FROM IMSI;
--YEAR까지 빼고 초기화
SELECT TO_CHAR(TRUNC(SYSDATE, 'YEAR'), 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
SELECT TO_CHAR(TRUNC(SYSDATE, 'YYYY'), 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
--MONTH까지 빼고 초기화
SELECT TO_CHAR(TRUNC(SYSDATE, 'MONTH'), 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
--현재 날짜의 일요일을 알려줌
SELECT TO_CHAR(TRUNC(SYSDATE, 'DAY'), 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
--DAY까지 빼고 초기화
SELECT TO_CHAR(TRUNC(SYSDATE, 'DD'), 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

--이번달 1일부터 마지막날짜 까지를 표시 해보자
SELECT TO_DATE(TRUNC(TO_DATE(:INDATE), 'MONTH')), (LEVEL - 1),
        TO_DATE(TRUNC(TO_DATE(:INDATE), 'MONTH')) + (LEVEL - 1)
FROM DUAL
CONNECT BY LEVEL <= TO_NUMBER(TO_CHAR(LAST_DAY(TO_DATE(:INDATE)), 'DD'))
;

SELECT TO_CHAR(LAST_DAY(TO_DATE('2021-12-05')),'DD') FROM DUAL;

SELECT MOD(124,7) FROM DUAL; -- 나머지
SELECT POWER(2,64) FROM DUAL; --제곱근
SELECT ABS(125),ABS(-125)  FROM DUAL; --절대값