SELECT * FROM PRODUCTS_TBL;
SELECT * FROM WHOLESALE_TBL;
SELECT * FROM BUY_TBL;
SELECT * FROM CUSTOMER_TBL;
SELECT * FROM SALES_TBL;
SELECT * FROM REGION_TBL;

--1.PRO_INDATE > 2021-02-05

SELECT TO_CHAR(PRO_INDATE, 'YYYY-MM-DD') AS INDATE FROM PRODUCTS_TBL;

--2. 2021년 월별 총 판매금액

SELECT TO_CHAR(B_INDATE,'YYYY-MM'), SUM(B_PRICE * B_QTY)
FROM BUY_TBL
GROUP BY TO_CHAR(B_INDATE,'YYYY-MM')
ORDER BY TO_CHAR(B_INDATE,'YYYY-MM')
;
---------------------------------------------------------------

SELECT A.INDATE, NVL(B.TLTPRICE,0) FROM 
(
SELECT TO_CHAR(TO_DATE('202101' + (LEVEL - 1),'YYYYMM'),'YYYY-MM') AS INDATE
FROM DUAL
CONNECT BY LEVEL <= 12
) A,
(
SELECT TO_CHAR(B_INDATE, 'YYYY-MM') AS INDATE, SUM(B_PRICE * B_QTY) AS TLTPRICE
FROM BUY_TBL
GROUP BY TO_CHAR(B_INDATE, 'YYYY-MM')
)B
WHERE A.INDATE = B.INDATE(+)
ORDER BY A.INDATE
;

--2.2021년 주차 총구매금액

SELECT T1.T1YEAR, T1.T1WEEK || '주차', NVL(T2PRICE,0)
FROM 
(
    SELECT TO_CHAR(TO_DATE('2021-01-01') + (LEVEL - 1), 'YYYY-MM') AS T1YEAR,TO_CHAR(TO_DATE('2021-01-01') + (LEVEL - 1), 'W') AS T1WEEK
    FROM DUAL
    CONNECT BY LEVEL <= 120
    GROUP BY TO_CHAR(TO_DATE('2021-01-01') + (LEVEL - 1), 'YYYY-MM'),TO_CHAR(TO_DATE('2021-01-01') + (LEVEL - 1), 'W')
) T1,
(
    SELECT TO_CHAR(B_INDATE, 'YYYY-MM') AS T2YYYY,TO_CHAR(B_INDATE, 'W') T2WW, SUM(B_PRICE * B_QTY) AS T2PRICE
    FROM BUY_TBL
    GROUP BY TO_CHAR(B_INDATE, 'YYYY-MM'),TO_CHAR(B_INDATE, 'W')
    ORDER BY TO_CHAR(B_INDATE, 'YYYY-MM')
) T2
WHERE T1.T1YEAR = T2.T2YYYY(+)
AND T1.T1WEEK = T2.T2WW(+)
ORDER BY T1.T1YEAR, T1.T1WEEK
;

--------------------------------------------------------------------

SELECT TO_CHAR(TO_DATE('2021-01-01'), 'WW') FROM DUAL; -- 가끔 52주차로 나옴
SELECT TO_CHAR(TO_DATE('2021-12-31'), 'WW') FROM DUAL; -- 가끔 53주차로 나옴

SELECT
    TO_CHAR(TO_DATE('2021-12-31'),'WW')
    -
    TO_CHAR(TO_DATE('2021-01-01'),'WW')
    + 1
FROM DUAL;

SELECT TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-12-31', 'YYYY-MM-DD')
FROM DUAL;

SELECT TRUNC(STSDATE, 'YEAR') FROM DUAL;
SELECT TRUNC(STSDATE, 'MONTH') FROM DUAL;
--올해 1월 1일
SELECT TRUNC(SYSDATE, 'YEAR') FROM DUAL;
--올해 12월 31일
SELECT TRUNC(
            TO_DATE(
                    TO_CHAR(SYSDATE, 'YYYY') + 1 || TO_CHAR(SYSDATE, 'MM') || TO_CHAR(SYSDATE, 'DD'),'YYYYMMDD'
                )
        ,'YEAR'
        ) - 1
FROM DUAL;



SELECT TO_CHAR(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-12-31', 'YYYY-MM-DD'),'WW')
FROM DUAL;

SELECT TO_CHAR(TRUNC(SYSDATE, 'YEAR'),'WW') FROM DUAL;

SELECT TO_NUMBER(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-12-31', 'YYYY-MM-DD'),'WW')) 
        - 
        TO_NUMBER(TO_CHAR(TRUNC(SYSDATE, 'YEAR'),'WW')) 
        + 1
FROM DUAL;

SELECT A.INWEEK, TO_CHAR(NVL(SUM(B.B_PRICE * B.B_QTY),0), 'FM999,999,999')
FROM
(
    SELECT TO_CHAR(SYSDATE, 'YYYY') || '-' || TO_CHAR(LEVEL, 'FM00') AS INWEEK
    FROM DUAL
    CONNECT BY LEVEL <=
    (
        SELECT TO_NUMBER(TO_CHAR(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-12-31', 'YYYY-MM-DD'),'WW')) 
            - 
            TO_NUMBER(TO_CHAR(TRUNC(SYSDATE, 'YEAR'),'WW')) 
            + 1
        FROM DUAL
    )
) A,
(
    SELECT TO_CHAR(B_INDATE, 'YYYY') || '-' || TO_CHAR(B_INDATE,'WW') AS INWEEK, B_PRICE, B_QTY
    FROM BUY_TBL
) B
WHERE A.INWEEK = B.INWEEK(+)
GROUP BY A.INWEEK
ORDER BY A.INWEEK
;

--2.2021년 분기별 총구매금액

SELECT T1.T1YYYY , T1.QQQ || '분기', NVL(T2.SUMPRICE,0)
FROM
(
    SELECT TO_CHAR('2021') AS T1YYYY,LEVEL AS QQQ 
    FROM DUAL
    CONNECT BY LEVEL <= 4
) T1,
(
    SELECT TO_CHAR(B_INDATE, 'YYYY'),TO_CHAR(B_INDATE, 'Q') AS QQ, SUM(B_PRICE * B_QTY) AS SUMPRICE
    FROM BUY_TBL
    GROUP BY TO_CHAR(B_INDATE, 'YYYY'),TO_CHAR(B_INDATE, 'Q')
    ORDER BY TO_CHAR(B_INDATE, 'Q')
) T2
WHERE T2.QQ(+) = T1.QQQ
ORDER BY T1.QQQ
;

--------------------------------------------------------
SELECT A.INDATE, NVL(SUM(B.B_PRICE * B.B_QTY),0)
FROM 
(
SELECT TO_CHAR(SYSDATE,'YYYY') || '-' || TO_CHAR(LEVEL,'FM00') AS INDATE
FROM DUAL
CONNECT BY LEVEL<= 4
) A,
(
SELECT TO_CHAR(B_INDATE,'YYYY') || '-' || TO_CHAR(TO_NUMBER(TO_CHAR(B_INDATE, 'Q')),'FM00') AS INDATE, B_PRICE, B_QTY
FROM BUY_TBL
) B
WHERE A.INDATE = B.INDATE(+)
GROUP BY A.INDATE
ORDER BY A.INDATE
;

--2.2021년 3월 2주차에서 가장 구매를 많이한 요일

SELECT *
FROM
(
    SELECT TO_CHAR(B_INDATE, 'YYYY-MM'),TO_CHAR(B_INDATE, 'W') || '주차' ,TO_CHAR(B_INDATE, 'DAY'), SUM(B_PRICE * B_QTY)
            , RANK() OVER(ORDER BY SUM(B_PRICE * B_QTY) DESC) AS RNK
    FROM BUY_TBL
    WHERE TO_CHAR(B_INDATE, 'YYYY-MM') = '2021-03' AND TO_CHAR(B_INDATE, 'W') = 2
    GROUP BY TO_CHAR(B_INDATE, 'YYYY-MM'),TO_CHAR(B_INDATE, 'W'),TO_CHAR(B_INDATE, 'DAY')
    ORDER BY TO_CHAR(B_INDATE, 'YYYY-MM')
)
WHERE RNK = 1
;

SELECT *
FROM
(
    SELECT BWEEK, SUM(B_PRICE * B_QTY)
            ,RANK() OVER(ORDER BY SUM(B_PRICE * B_QTY) DESC) AS RNK
    FROM
    (
        SELECT B_PRICE,B_QTY, TO_CHAR(B_INDATE,'DAY') AS BWEEK
                ,TO_CHAR(B_INDATE,'YYYY')|| TO_CHAR(B_INDATE,'MM') || TO_CHAR(B_INDATE,'W')
        FROM BUY_TBL
        WHERE TO_CHAR(B_INDATE,'YYYY')|| TO_CHAR(B_INDATE,'MM') || TO_CHAR(B_INDATE,'W') = '2021032'
    )
    GROUP BY BWEEK
)
WHERE RNK = 1
;