--1. TO_CHAR 함수
--데이터베이스 - 데이터차입이 존재 - 숫자타입, 문자타입, 날짜타입

SELECT '1234' AS TEST FROM DUAL;
SELECT 1234 AS TEST FROM DUAL;

SELECT '1234' + 1234 FROM DUAL;

SELECT TO_DATE('2021-04-16') - 2 AS DT FROM DUAL;
SELECT '2021-04-16' + 2 FROM DUAL; -- 안돼요
SELECT '20210416' + 2 FROM DUAL; -- 돼요

--1.TO_CHAR를 날짜로 활용

SELECT SYSDATE FROM DUAL;

    --1.1 날짜표시
    
    SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') FROM DUAL;
    SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD') FROM DUAL;
    SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM DUAL;
    
    SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS') FROM DUAL;
    SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;-- 24시 체제
    
    SELECT TO_CHAR('2021-05-05', 'YYYYMMDD') FROM DUAL;-- DATE 타입이 와야함
    SELECT TO_CHAR(TO_DATE('2021-05-05'), 'YYYYMMDD') FROM DUAL;
    
--2., 표시

SELECT TO_CHAR('9745111000', '999,999,999,999')FROM DUAL;
SELECT TO_CHAR('9745111000', 'FM999,999,999,999')FROM DUAL;-- 공백제거
SELECT TO_CHAR('9745111000', 'FML999,999,999,999')FROM DUAL;-- 한화

--3. 000 표시

--0001 0002 0003 0004 ~~~~~~~~ 017 018 019 ~~~~ 123 124 125
SELECT TO_CHAR(77,'0000') FROM DUAL;
SELECT TO_CHAR(77,'FM0000') FROM DUAL; -- 공백제거

SELECT TO_CHAR(89087) FROM DUAL; -- 숫자를 문자로 바꿈
SELECT TO_CHAR(89087) || '원' FROM DUAL;

--4. 2021년 04월 16일
SELECT TO_CHAR(SYSDATE, 'YYYY') || '년' || TO_CHAR(SYSDATE, 'MM') || '월'
        || TO_CHAR(SYSDATE, 'DD') || '일'
FROM DUAL;

--2021년 04월 05일 -> 2021년 4월 5일

SELECT TO_CHAR(SYSDATE, 'FMMM') FROM DUAL;
SELECT TO_CHAR(TO_DATE('2021-04-05'), 'FMDD') FROM DUAL;

--5. 요일반환

SELECT TO_CHAR(SYSDATE, 'D') FROM DUAL; -- 1:일요일 ~ 7:토요일
SELECT TO_CHAR(SYSDATE, 'DY') FROM DUAL; -- 한글로 한글자로 요일을 표시
SELECT TO_CHAR(SYSDATE, 'DAY') FROM DUAL; -- 한글로 요일을 표시

--6. 1년을 기준으로 2021-01-01 을 기준으로 오늘이 몇일째이지?

SELECT TO_CHAR(SYSDATE, 'DDD') FROM DUAL; -- 오늘이 몇일째이지?
SELECT TO_CHAR(SYSDATE, 'WW') FROM DUAL; -- 오늘이 1년단위 몇주째이지? 1년은 총 52주
SELECT TO_CHAR(SYSDATE, 'W') FROM DUAL; -- 오늘이 한달단위 몇주째이지?
SELECT TO_CHAR(SYSDATE, 'Q') FROM DUAL; -- 오늘이 몇분기이지?

--7.년 월 일 요일 가져오기

SELECT TO_CHAR(SYSDATE, 'MON') FROM DUAL; -- 월
SELECT TO_CHAR(SYSDATE, 'YEAR') FROM DUAL; -- 영문 년도
SELECT TO_CHAR(SYSDATE, 'DL') FROM DUAL; -- 년월일요일

--8. 세기

SELECT TO_CHAR(SYSDATE, 'CC') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'SCC') FROM DUAL;

-- AD BC

SELECT TO_CHAR(SYSDATE, 'AD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'BC') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DS') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'RM') FROM DUAL; -- 달을 로마자로 표시

SELECT TO_CHAR(SYSDATE, 'YYYY') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'RRRR') FROM DUAL;

--영어로 표시
SELECT TO_CHAR(SYSDATE, 'DDSP') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'MMSP') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYYSP') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DDTH') FROM DUAL;