--문자열 함수들

--1. CONCAT

SELECT CONCAT('AAAA','BBBB') FROM DUAL;
SELECT PRO_COMPANY || ' ' || PRO_NAME FROM PRODUCTS_TBL;
SELECT CONCAT(PRO_COMPANY || ' ',PRO_NAME) FROM PRODUCTS_TBL;

--2. INITCAP -- 첫글자만 대문자로 바꾸고 나머지 문자는 전부 소문자로 바꾼다.

SELECT INITCAP('AAAAAA') FROM DUAL;
SELECT INITCAP('aaaaaa') FROM DUAL;
SELECT INITCAP('bBbBbBbBbb') FROM DUAL;
SELECT INITCAP('tHIS IS A BOOK') FROM DUAL;

--3. UPPER -- 전체영문을 전부 다 대문자로 바꾼다

SELECT UPPER('aaaaa') FROM DUAL;
SELECT UPPER('AAAAA') FROM DUAL;
SELECT UPPER('AAaaAAnnNN') FROM DUAL;
SELECT UPPER('THIS IS A BOOK') FROM DUAL;
SELECT UPPER('this is a book') FROM DUAL;


--4. LOWER -- 전체영문을 전부다 소문자로 바꾼다.

SELECT LOWER('aaaaa') FROM DUAL;
SELECT LOWER('AAAAA') FROM DUAL;
SELECT LOWER('AAaaaaa') FROM DUAL;
SELECT LOWER('THIS IS A BOOK') FROM DUAL;
SELECT LOWER('this is a book') FROM DUAL;

--★5. LPAD -- 문자열에 특정문자를 추가 > 앞을 비워서 추가함

SELECT LPAD('ABCDEF', 8, '@') FROM DUAL;
SELECT LPAD('ABCDEF', 12, '@') FROM DUAL;
SELECT LPAD('ABCDEF', 9, ' ') FROM DUAL; -- 공백을 만들 때 사용
SELECT TO_CHAR(12, 'FM0000') FROM DUAL;
SELECT LPAD(12, 4, '0')FROM DUAL;
SELECT LPAD(7, 4, '0')FROM DUAL;
SELECT LPAD(122, 4, '0')FROM DUAL;

--6. RPAD --특정문자를 오른쪽에 추가

SELECT RPAD('AAA', 6, '%') FROM DUAL;

--7. LTRIM -- 공백제거 > 왼쪽앞에 있는 특정문자를 제거

SELECT LTRIM('    123456') FROM DUAL;
SELECT LTRIM('AAACCCBBBDDD', 'A') FROM DUAL;
SELECT LTRIM('홍길동', '홍') FROM DUAL;

--8. RTRIM -- 오른쪽공백제거, 오른쪽 끝에 있는 특정문자를 제거

SELECT RTRIM('12345       ') FROM DUAL;
SELECT RTRIM('12345@@@', '@') FROM DUAL;
SELECT RTRIM('가나다다다', '다') FROM DUAL;
SELECT RTRIM('가나다다다', '나') FROM DUAL;

--9. REPLACE -- 특정문자를 대체하는 함수

SELECT REPLACE('ABCD@@BDEF', '@', '-') FROM DUAL;
SELECT REPLACE('ABCD@@BDEF', '@', '%%%') FROM DUAL;
SELECT REPLACE('ABCD@@BDEF', '@@', '%') FROM DUAL;
SELECT REPLACE('ABCD@@BDEF', '@@', ' ') FROM DUAL;
SELECT REPLACE('ABCD@@BDEF', '@@', '') FROM DUAL;
SELECT REPLACE('홍길동', '길', '상') FROM DUAL;

--★10. SUBSTR

SELECT SUBSTR('123456789', 1, 5) FROM DUAL;
SELECT SUBSTR('123456789123213', 4) FROM DUAL;
SELECT SUBSTR('123456789123213', -7) FROM DUAL;
SELECT SUBSTR('123456789123213', -7, 3) FROM DUAL;

--11. LENGTH, LENGTHB -- 특정문자열의 길이 / BYTE

--길이
SELECT LENGTH(' 123456789 ') FROM DUAL;
SELECT LENGTH('123456789') FROM DUAL;
SELECT LENGTH('홍길동') FROM DUAL;

--BYTE
SELECT LENGTHB(' 123456789 ') FROM DUAL;
SELECT LENGTHB('123456789') FROM DUAL;
SELECT LENGTHB('홍길동') FROM DUAL; -- 한글은 3BYTE
SELECT LENGTHB('TOM') FROM DUAL;


--★12. INSTR 자바스크립트에서 INDEXOF > 특정문자열의 특정문자가 포함되어있는지 확인

SELECT 'ABC@BCD@RDF@DFDE' FROM DUAL;
SELECT INSTR('ABC@BCD@RDF@DFDE', '@') FROM DUAL; -- 앞에서 찾는다
SELECT INSTR('ABC@BCD@RDF@DFDE', '@', -1) FROM DUAL; -- 뒤에서 찾는다

--13.TRIM

SELECT TRIM('   AAABBBCCC    ') FROM DUAL;
SELECT TRIM('AAABBBCCCAAA', 'A') FROM DUAL; -- 안됨
SELECT RTRIM(LTRIM('AAABBBCCCAAA', 'A'),'A') FROM DUAL;

SELECT LTRIM(LTRIM(W_ID, 'W'), '0') FROM BUY_TBL;

SELECT TO_NUMBER(SUBSTR(PRO_ID, 2)) FROM BUY_TBL;
SELECT LTRIM(LTRIM(PRO_ID, 'P'), '0') FROM BUY_TBL;


--이름에 '갑'이라는 글자 포함된 사람

SELECT * FROM CUSTOMER_TBL
WHERE C_NAME LIKE '%갑%'
;

--INSTR사용

SELECT * FROM CUSTOMER_TBL
WHERE INSTR(C_NAME, '갑') != 0
;