--지역을 추가하는 프로시저
CREATE OR REPLACE PROCEDURE PROC_INSERT_REGION
(
    IN_R_ID     IN      VARCHAR2,
    IN_R_NAME   IN      VARCHAR2
)
AS
BEGIN
    INSERT INTO REGION_TBL
    (R_ID, R_NAME)
    VALUES
    (IN_R_ID, IN_R_NAME)
    ;
    
END PROC_INSERT_REGION
;