--PRODUCTS_TBL INSERT 하는 프로시져를 만들자
CREATE OR REPLACE PROCEDURE PROC_INSERT_PRODUCTS
(
    IN_PRO_NAME        IN      VARCHAR2,
    IN_PRO_COMPANY     IN      VARCHAR2,
    IN_PRO_VOL         IN      VARCHAR2,
    IN_PRO_INDATE      IN      DATE
)
AS
    
    V_PRO_ID    CHAR(6);
    
BEGIN

    SELECT 'P' || TO_CHAR(TO_NUMBER(SUBSTR(MAX(PRO_ID),2))+1,'FM00000')
    INTO V_PRO_ID
    FROM PRODUCTS_TBL
    ;

    INSERT INTO PRODUCTS_TBL
    (PRO_ID, PRO_NAME, PRO_COMPANY, PRO_VOL, PRO_INDATE)
    VALUES
    (V_PRO_ID, IN_PRO_NAME, IN_PRO_COMPANY, IN_PRO_VOL, IN_PRO_INDATE)
    ;
    
END PROC_INSERT_PRODUCTS
;

CREATE OR REPLACE PROCEDURE PROC_UPDATE_PRODUCTS
(
    IN_PRO_ID       IN      VARCHAR2,
    IN_PRO_NAME     IN      VARCHAR2,
    IN_PRO_COMPANY  IN      VARCHAR2,
    IN_PRO_VOL      IN      VARCHAR2,
    IN_PRO_INDATE   IN      DATE
)
AS
BEGIN
    UPDATE PRODUCTS_TBL
    SET PRO_NAME = IN_PRO_NAME,
        PRO_COMPANY = IN_PRO_COMPANY,
        PRO_VOL = IN_PRO_VOL,
        PRO_INDATE = IN_PRO_INDATE   
    WHERE PRO_ID = IN_PRO_ID
    ;
END PROC_UPDATE_PRODUCTS
;

SELECT *
FROM BUY_TBL
;

SELECT B_IDX 
    FROM BUY_TBL
    WHERE PRO_ID = 'P00002' AND W_ID = 'W00002'
    ;