CREATE OR REPLACE PROCEDURE PROC_DELETE_CUSTOMER
(
    IN_C_ID     IN      VARCHAR2
)
AS
BEGIN
    
    DELETE FROM CUSTOMER_TBL
    WHERE C_ID = IN_C_ID
    ;

END PROC_DELETE_CUSTOMER
;

CREATE OR REPLACE PROCEDURE PROC_DELETE_PRODUCTS
(
    IN_PRO_ID     IN      VARCHAR2
)
AS
BEGIN
    
    DELETE FROM PRODUCTS_TBL
    WHERE PRO_ID = IN_PRO_ID
    ;
    
END PROC_DELETE_PRODUCTS
;

CREATE OR REPLACE PROCEDURE PROC_DELETE_REGION
(
    IN_R_ID     IN      VARCHAR2
)
AS
BEGIN
    
    DELETE FROM REGION_TBL
    WHERE R_ID = IN_R_ID
    ;
    
END PROC_DELETE_REGION
;

CREATE OR REPLACE PROCEDURE PROC_DELETE_WHOLESALE
(
    IN_W_ID     IN      VARCHAR2
)
AS
BEGIN
    
    DELETE FROM WHOLESALE_TBL
    WHERE W_ID = IN_W_ID
    ;
    
END PROC_DELETE_WHOLESALE
;

CREATE OR REPLACE PROCEDURE PROC_INSERT_WHOLESALE
(
    IN_W_NAME       IN      VARCHAR2,
    IN_W_REGION     IN      VARCHAR2,
    IN_W_YEAR       IN      VARCHAR2
)
AS
    
    V_W_ID      CHAR(6);

BEGIN
    
    SELECT 'W' || TO_CHAR(TO_NUMBER(SUBSTR(MAX(W_ID),2)) + 1,'FM00000')
    INTO    V_W_ID
    FROM WHOLESALE_TBL
    ;
    
    INSERT INTO WHOLESALE_TBL
    (W_ID, W_NAME, W_REGION, W_YEAR)
    VALUES
    (V_W_ID, IN_W_NAME, IN_W_REGION, IN_W_YEAR)
    ;
    
END PROC_INSERT_WHOLESALE
;

CREATE OR REPLACE PROCEDURE PROC_UPDATE_REGION
(
    IN_R_ID     IN      VARCHAR2,
    IN_R_NAME   IN      VARCHAR2
)
AS
BEGIN

    UPDATE REGION_TBL
    SET R_NAME = IN_R_NAME
    WHERE R_ID = IN_R_ID
    ;
    
END PROC_UPDATE_REGION
;

CREATE OR REPLACE PROCEDURE PROC_UPDATE_WHOLESALE
(
    IN_W_ID         IN      VARCHAR2,
    IN_W_NAME       IN      VARCHAR2,
    IN_W_REGION     IN      VARCHAR2,
    IN_W_YEAR       IN      VARCHAR2
)
AS
BEGIN
    
    UPDATE WHOLESALE_TBL
    SET W_NAME = IN_W_NAME,
        W_REGION = IN_W_REGION,
        W_YEAR = IN_W_YEAR
    WHERE   W_ID =  IN_W_ID
    ;
    
END PROC_UPDATE_WHOLESALE
;

CREATE OR REPLACE PROCEDURE PROC_UPDATE_BUY_TBL
(
    IN_PRO_ID       IN      VARCHAR2,
    IN_W_ID         IN      VARCHAR2,
    IN_B_IDX        IN      VARCHAR2,
    IN_B_PRICE      IN      VARCHAR2,
    IN_B_QTY        IN      VARCHAR2,
    IN_B_INDATE     IN      VARCHAR2,
    IN_B_CONTENT    IN      VARCHAR2
)
AS
BEGIN
    
    UPDATE  BUY_TBL
    SET     B_PRICE     =   IN_B_PRICE,
            B_QTY       =   IN_B_QTY,
            B_INDATE    =   IN_B_INDATE
    WHERE   PRO_ID = IN_PRO_ID AND W_ID = IN_W_ID AND B_IDX = IN_B_IDX
    ;
END PROC_UPDATE_BUY_TBL
;

CREATE OR REPLACE PROCEDURE PROC_DELETE_BUY_TBL
(
    IN_PRO_ID       IN      VARCHAR2,
    IN_W_ID         IN      VARCHAR2,
    IN_B_IDX        IN      VARCHAR2
)
AS
BEGIN

    DELETE FROM BUY_TBL
    WHERE PRO_ID = IN_PRO_ID AND W_ID = IN_W_ID AND B_IDX = IN_B_IDX
    ;
    
END PROC_DELETE_BUY_TBL
;

CREATE OR REPLACE PROCEDURE PROC_INSERT_SALES_TBL
(
    IN_C_ID     IN      VARCHAR2,
    IN_PRO_ID   IN      VARCHAR2,
    IN_S_PRICE     IN      NUMBER,
    IN_S_QTY       IN      NUMBER
)
AS

    V_S_IDX     NUMBER(4,0);
    
BEGIN
    
    SELECT MAX(S_IDX) + 1
    INTO V_S_IDX
    FROM SALES_TBL
    WHERE C_ID = IN_C_ID AND PRO_ID = IN_PRO_ID
    ;
    
    INSERT INTO SALES_TBL
    (C_ID, PRO_ID, S_IDX, S_PRICE, S_QTY, S_OUTDATE)
    VALUES
    (IN_C_ID, IN_PRO_ID, V_S_IDX, IN_S_PRICE, IN_S_QTY, SYSDATE)
    ;
    
END PROC_INSERT_SALES_TBL
;

CREATE OR REPLACE PROCEDURE PROC_DELETE_SALES_TBL
(
    IN_C_ID        IN      VARCHAR2,
    IN_PRO_ID      IN      VARCHAR2,
    IN_S_IDX          IN      VARCHAR2
)
AS
BEGIN

    DELETE FROM SALES_TBL
    WHERE C_ID = IN_C_ID AND PRO_ID = IN_PRO_ID AND S_IDX = IN_S_IDX
    ;
    
END PROC_DELETE_SALES_TBL
;

CREATE OR REPLACE PROCEDURE PROC_UPDATE_SALES_TBL
(
    IN_PRO_ID       IN      VARCHAR2,
    IN_C_ID         IN      VARCHAR2,
    IN_S_IDX        IN      VARCHAR2,
    IN_S_PRICE      IN      VARCHAR2,
    IN_S_QTY        IN      VARCHAR2,
    IN_S_OUTDATE     IN      VARCHAR2
)
AS
BEGIN

    UPDATE  SALES_TBL
    SET     S_PRICE     =   IN_S_PRICE,
            S_QTY       =   IN_S_QTY,
            S_OUTDATE    =   IN_S_OUTDATE
    WHERE   PRO_ID = IN_PRO_ID AND C_ID = IN_C_ID AND S_IDX = IN_S_IDX
    ;

END PROC_UPDATE_SALES_TBL
;

CREATE OR REPLACE PROCEDURE PROC_SELECT_BUY_TBL
(
    IN_PRO_ID   IN      VARCHAR2,
    IN_W_ID     IN      VARCHAR2,
    B_IDX       IN      VARCHAR2,
    OUT_CUR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN OUT_CUR FOR
    SELECT T2.PRO_NAME, T3.W_NAME
    FROM BUY_TBL T1, PRODUCTS_TBL T2, WHOLESALE_TBL T3
    WHERE T1.PRO_ID = T2.PRO_ID
    AND T1.W_ID = T3.W_ID
    AND T1.PRO_ID = IN_PRO_ID
    ;

END PROC_SELECT_BUY_TBL
;