CREATE OR REPLACE PROCEDURE PROC_UPDATE_CUSTOMER
(
    IN_C_ID     IN  VARCHAR2,
    IN_C_NAME   IN  VARCHAR2,
    IN_C_BIRTH  IN  DATE,
    IN_C_REGION IN  VARCHAR2,
    IN_C_GENDER IN  VARCHAR2
)
AS

BEGIN
    
    UPDATE CUSTOMER_TBL
    SET C_NAME = IN_C_NAME,
        C_BIRTH = IN_C_BIRTH,
        C_REGION = IN_C_REGION,
        C_GENDER = IN_C_GENDER
    WHERE C_ID = IN_C_ID
    ;
    
END PROC_UPDATE_CUSTOMER
;