--회원별 구매 금액
--회원, 월별기간

SELECT T1.C_ID, T1.C_NAME, SUM(T2.S_PRICE * T2.S_QTY) AS TLTPRICE
FROM CUSTOMER_TBL T1, SALES_TBL T2
WHERE T1.C_ID = T2.C_ID(+)
GROUP BY T1.C_ID, T1.C_NAME
;
SELECT C_ID, C_NAME, NVL(SUM(S_PRICE * S_QTY),0) FROM
(
SELECT T1.C_ID, T1.C_NAME, T2.S_PRICE, T2.S_QTY, TO_CHAR(T2.S_OUTDATE, 'YYYYMM') AS S_OUTMONTH
FROM CUSTOMER_TBL T1, SALES_TBL T2
WHERE T1.C_ID = T2.C_ID(+)
AND T1.C_ID = 'C00006'
AND (
        TO_CHAR(T2.S_OUTDATE, 'YYYYMM') >= '202102' AND TO_CHAR(T2.S_OUTDATE, 'YYYYMM') <= '202104'
        OR 
        T2.S_OUTDATE IS NULL
    )
)
GROUP BY C_ID, C_NAME
;

CREATE OR REPLACE PROCEDURE PROC_TLTPRICE_PER_CUSTOMER
(
    IN_C_ID     IN      VARCHAR2,
    IN_B_MONTH  IN      VARCHAR2,
    IN_E_MONTH  IN      VARCHAR2,
    O_CUR       OUT     SYS_REFCURSOR
)
AS
BEGIN
    
    OPEN O_CUR FOR
    SELECT C_ID, C_NAME, NVL(SUM(S_PRICE * S_QTY),0) FROM
    (
        SELECT T1.C_ID, T1.C_NAME, T2.S_PRICE, T2.S_QTY, TO_CHAR(T2.S_OUTDATE, 'YYYYMM') AS S_OUTMONTH
        FROM CUSTOMER_TBL T1, SALES_TBL T2
        WHERE T1.C_ID = T2.C_ID(+)
        AND T1.C_ID = IN_C_ID
        AND (
        (TO_CHAR(T2.S_OUTDATE, 'YYYYMM') >= IN_B_MONTH AND TO_CHAR(T2.S_OUTDATE, 'YYYYMM') <= IN_E_MONTH)
        OR 
        T2.S_OUTDATE IS NULL
        )
    )
GROUP BY C_ID, C_NAME
;
    
END PROC_TLTPRICE_PER_CUSTOMER
;