CREATE OR REPLACE PROCEDURE PROC_INS_PROFIT
(
    IN_YYYYMM        IN      VARCHAR2
)
AS

    V_IDX       NUMBER(3);
    
BEGIN

    /* 한번에 다넣기
    SELECT ROW_NUMBER()OVER(ORDER BY T1.BSDATE), T1.BSDATE, NVL(TLTPRICE, 0) AS TLTPICE
    FROM
    (
    SELECT TO_CHAR(TRUNC(SYSDATE, 'YEAR'),'YYYYMM') + (LEVEL -1) AS BSDATE
    FROM DUAL
    CONNECT BY LEVEL <= TO_NUMBER(TO_CHAR(SYSDATE, 'MM'))
    ) T1,
    (
    SELECT TO_CHAR(S_OUTDATE, 'YYYYMM') AS OUTDATE, SUM(S_PRICE * S_QTY) AS TLTPRICE
    FROM SALES_TBL
    GROUP BY TO_CHAR(S_OUTDATE, 'YYYYMM')
    ) T2
    WHERE T1.BSDATE = T2.OUTDATE(+)
    ORDER BY T1.BSDATE
    ;
    */
    
    SELECT NVL(MAX(PR_ID), 0) + 1
    INTO V_IDX
    FROM PROFIT_TBL
    ;
    
    INSERT INTO PROFIT_TBL
    SELECT V_IDX, T1.BSDATE, NVL(TLTPRICE, 0) AS TLTPICE
    FROM
    (
    SELECT TO_CHAR(TRUNC(SYSDATE, 'YEAR'),'YYYYMM') + (LEVEL -1) AS BSDATE
    FROM DUAL
    CONNECT BY LEVEL <= TO_NUMBER(TO_CHAR(SYSDATE, 'MM'))
    ) T1,
    (
    SELECT TO_CHAR(S_OUTDATE, 'YYYYMM') AS OUTDATE, SUM(S_PRICE * S_QTY) AS TLTPRICE
    FROM SALES_TBL
    GROUP BY TO_CHAR(S_OUTDATE, 'YYYYMM')
    ) T2
    WHERE T1.BSDATE = T2.OUTDATE(+)
    AND T1.BSDATE = IN_YYYYMM
    ORDER BY T1.BSDATE
    ;
    
END PROC_INS_PROFIT
;
