--회원별로 CUSTOMER_TBL에 C_POINT 값을 입력하는 프로시저 만들자 -> POINT_TBL INSERT
--오늘의 숙제

CREATE OR REPLACE PROCEDURE PROC_INSERT_POINT
(
    IN_C_ID     IN      VARCHAR2
)
AS
BEGIN
    
    SELECT C_ID, SUM(POINT)
    FROM
    (
    SELECT T3.C_ID, T3.C_NAME, NVL(SUM(T1.S_PRICE * T1.S_QTY)*(T2.PRO_POINT/100),0) AS POINT
    FROM SALES_TBL T1, PRODUCTS_TBL T2, CUSTOMER_TBL T3
    WHERE T1.PRO_ID = T2.PRO_ID(+)
    AND T1.C_ID(+) = T3.C_ID
    GROUP BY T3.C_ID, T3.C_NAME, T1.PRO_ID, T2.PRO_POINT
    )
    GROUP BY C_ID
    ;
    
END
;
