--답변형게시판
--INSERT할 때 로직이 만들어진다

SELECT * FROM PARTS_TBL;

--총무 4팀

CREATE OR REPLACE PROCEDURE PROC_INS_PART
(
    IN_PART_NAEM        IN      VARCHAR2,
    IN_PART_LVL         IN      NUMBER,
    IN_PART_SEQ         IN      NUMBER,
    IN_PARENT_PART_ID   IN      VARCHAR2
)
AS

    V_NEW_ID        CHAR(6);

BEGIN
    
    --1. NEW PART ID 생성
    
    SELECT 'PT' || TO_CHAR(TO_NUMBER(SUBSTR(NVL(MAX(PART_ID),'PT0000'),3)) +1, 'FM0000')
    INTO V_NEW_ID
    FROM PARTS_TBL
    ;
    
    --2. SEQ UPDATE
    
    UPDATE PARTS_TBL
    SET PART_SEQ = PART_SEQ + 1
    WHERE PARENT_PART = IN_PARENT_PART_ID
    AND PART_SEQ >= IN_PART_SEQ
    ;
    
    INSERT INTO PARTS_TBL
    (PART_ID, PART_NAEM, PART_LVL, PART_SEQ, PARENT_PART_ID)
    VALUES
    (V_NEW_ID, IN_PART_NAEM, IN_PART_LVL, IN_PART_SEQ, IN_PARENT_PART_ID)
    ;
END PROC_INS_PART
;

SELECT LPAD(PART_NAME, LENGTH(PART_NAME) + PART_LVL,'   ') FROM PARTS_TBL
START WITH PARENT_PART_ID IS NULL
CONNECT BY PRIOR PART_ID = PARENT_PART_ID
;