CREATE TABLE G_CLASS
(
    CLASS_ID        CHAR(5)         NOT NULL,
    CLASS_NAME      VARCHAR(30)     NOT NULL,
    YEAR_PRICE      NUMBER(10)      NOT NULL
);

INSERT INTO (CLASS_ID, CLASS_NAME, YEAR_PRICE) VALUES ('CL001','사장',10000000);
INSERT INTO (CLASS_ID, CLASS_NAME, YEAR_PRICE) VALUES ('CL002','부장',7000000);
INSERT INTO (CLASS_ID, CLASS_NAME, YEAR_PRICE) VALUES ('CL003','차장',6000000);
INSERT INTO (CLASS_ID, CLASS_NAME, YEAR_PRICE) VALUES ('CL004','과장',5000000);
INSERT INTO (CLASS_ID, CLASS_NAME, YEAR_PRICE) VALUES ('CL005','대리',4000000);
INSERT INTO (CLASS_ID, CLASS_NAME, YEAR_PRICE) VALUES ('CL006','사원',3000000);
INSERT INTO (CLASS_ID, CLASS_NAME, YEAR_PRICE) VALUES ('CL007','인턴',2000000);

CREATE TABLE G_PART
(
    PART_ID         CHAR(5)         NOT NULL,
    PART_NAME       VARCHAR(30)     NOT NULL,
    PART_LVL        NUMBER(3)       NOT NULL,
    PART_SEQ        NUMBER(3)       NOT NULL,
    PARENT_PART_ID  CHAR(5)         NULL
);

INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT001','ROOT', 0, 1, NULL);
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT002','전체인사부', 1, 2, 'PT001');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT003','전체기획부', 1, 1, 'PT001');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT004','전체판매부', 1, 3, 'PT001');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT005','액션판매부', 2, 6, 'PT004');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT006','캐주얼판매부', 2, 7, 'PT004');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT007','롤플레잉판매부', 2, 1, 'PT004');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT008','스포츠판매부', 2, 2, 'PT004');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT009','퍼즐판매부', 2, 8, 'PT004');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT010','어드벤처판매부', 2, 5, 'PT004');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT011','시물레이션판매부', 2, 3, 'PT004');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT012','아케이드판매부', 2, 4, 'PT004');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT013','FPS판매부', 2, 10, 'PT004');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT014','호러판매부', 2, 9, 'PT004');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT015','액션판매광고팀', 3, 1, 'PT005');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT016','액션배송팀', 3, 2, 'PT005');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT017','액션재고관리팀', 3, 3, 'PT005');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT018','액션재고구매팀', 3, 4, 'PT005');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT019','FPS판매광고팀', 3, 1, 'PT013');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT020','FPS배송팀', 3, 2, 'PT013');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT021','FPS재고관리팀', 3, 3, 'PT013');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT017','액션재고구매팀-1', 4, 1, 'PT018');
INSERT INTO (PART_ID, PART_NAME, PART_LVE, PART_SEQ, PARENT_PART_ID) VALUES('PT017','액션재고구매팀-2', 4, 2, 'PT018');

CREATE TABLE G_EMPLOYEE
(
    E_ID        CHAR(5)     NOT NULL,
    E_NAME      VARCHAR(30) NOT NULL,
    CLASS_ID    CHAR(5)     NOT NULL,
    PART_ID     CHAR(5)     NOT NULL
)

INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0001','스타사장','CL001', 'PT001');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0002','커맨드센터','CL002', 'PT002');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0003','넥서스','CL002', 'PT003');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0004','해처리','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0005','드론','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0006','저글링','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0007','히드라','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0008','럴커','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0009','라바','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0010','뮤탈리스크','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0011','디바우러','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0012','가디언','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0013','울트라리스크','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0014','감염된테란','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0015','성큰','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0016','스포닝풀','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0017','뮤탈둥지','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0018','퀸','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0019','레어','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0020','하이브','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0021','캐리건','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0022','질럿','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0023','드라군','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0024','캐리어','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0025','스카우터','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0026','메딕','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0027','파이어뱃','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0028','벌처','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0029','골리앗','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0030','시즈탱크','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0031','고스트','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0032','해처리','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0033','해처리','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0034','해처리','CL002', 'PT004');
INSERT INTO G_EMPLOYEE (E_ID, E_NAME, CLASS_ID, PART_ID) VALUES('E0035','해처리','CL002', 'PT004');
