SELECT * FROM CUSTOMER_TBL;
SELECT * FROM SALES_TBL;
SELECT * FROM PRODUCTS_TBL;

--고객별 상품별 구매횟수

SELECT *
FROM CUSTOMER_TBL T1, SALES_TBL T2, PRODUCTS_TBL T3
WHERE T1.C_ID = T2.C_ID(+)
AND T2.PRO_ID(+) = T3.PRO_ID
;
SELECT * FROM
(
SELECT T1.C_ID, T1.C_NAME, T2.PRO_ID, T2.S_PRICE, T2.S_QTY
FROM CUSTOMER_TBL T1, SALES_TBL T2, PRODUCTS_TBL T3
WHERE T1.C_ID = T2.C_ID(+)
) A, PRODUCTS_TBL B
WHERE A.PRO_ID(+) = B.PRO_ID
;
-----이렇게 하면 똑같음
