SELECT * FROM WHOLESALE_TBL;
SELECT * FROM BUY_TBL;
SELECT PRO_ID, PRO_NAME, PRO_POINT, PKG_WHOLESALE.FN_CAL_POINT_RATE(PRO_POINT, 3) AS PRO_POINT 
FROM PRODUCTS_TBL;

SELECT FN_ADD(6,7) AS RESULT FROM DUAL;

SELECT C_ID, C_NAME, C_POINT,
       PKG_WHOLESALE.FN_CAL_POINT_RATE(NVL(C_POINT,0), 2) AS POINT
FROM CUSTOMER_TBL;