CREATE TABLE BOARDS
(
    BID         NUMBER(5)       PRIMARY KEY,
    BTITLE      VARCHAR2(100)   NOT NULL,
    PARENTID    NUMBER(5)       NOT NULL
);

DROP TABLE BOARDS;

INSERT INTO BOARDS VALUES(1, '1-0', 0);
INSERT INTO BOARDS VALUES(2, '2-0', 0);
INSERT INTO BOARDS VALUES(3, '3-0', 0);

SELECT * FROM BOARDS;

SELECT *
FROM BOARDS
START WITH PARENTID = 0
CONNECT BY PRIOR BID = PARENTID
ORDER SIBLINGS BY BID ASC
;
 
SELECT BID, LPAD(BTITLE, LENGTH(BTITLE) + LEVEL, ' '), PARENTID, LEVEL
FROM BOARDS
START WITH PARENTID = 0
CONNECT BY PRIOR BID = PARENTID
ORDER SIBLINGS BY BID DESC
;

--COMMIT;

--1. 첫번째 새글(1-0)에 첫번째 답글을 달자

INSERT INTO BOARDS VALUES(4, '1-0-1', 1);

--2. 두번째 새글(2-0)에 첫번째 답글을 달자

INSERT INTO BOARDS VALUES(5, '2-0-1', 2);

--3. 첫번째 새글(1-0)에 첫번째 답글에 첫번째 답글을 달자

INSERT INTO BOARDS VALUES(6, '1-0-1-1', 4);

--4. 첫번째 새글(1-0)에 두번째 답글을 달자

INSERT INTO BOARDS VALUES(7, '1-0-2', 1);