SELECT * FROM CUSTOMER_TBL;

SELECT * FROM SALES_TBL;
/*
--1. SALES_TBL DATE 가 있는지 확인
    SELECT COUNT(*) INTO V_CNT
    FROM SALES_TBL
    WHERE C_ID = IN_C_ID
    ;
    
    IF V_CNT = 0 THEN
        
        DELETE FROM CUSTOMER_TBL
        WHERE C_ID = IN_C_ID
        ;
        
    ELSE
    
        UPDATE CUSTOMER_TBL
        SET C_USE_YN = 'N'
        WHERE C_ID = IN_C_ID
        ;
    
    END IF
    ;
*/
/*
MERGE INTO CUSTOMER_TBL T1
USING (
    SELECT * FROM SALES_TBL
    WHERE C_ID = IN_C_ID
) T2
ON(T1.C_ID = T2.C_ID)
WHEN MATCHED THEN
    UPDATE SET C_USE_YN = 'N'
    DELETE WHERE T1.C_ID = IN_C_ID
WHEN NOT MATCHED THEN
    INSERT(C_ID)VALUES('AAAA')
;
DELETE를 사용할 수 없다
*/

UPDATE CUSTOMER_TBL
SET C_USE_YN = 'N'
WHERE C_ID = IN_C_ID
;

DELETE FROM CUSTOMER_TBL T1
WHERE NOT EXISTS
(
    SELECT 1 FROM SALES_TBL
    WHERE C_ID = T1.C_ID
)
AND C_ID = IN_C_ID
;