--SEQUENCE
CREATE SEQUENCE SEQ_TEST
INCREMENT BY 1
START WITH 1
MAXVALUE 10000
MINVALUE 1;
--숫자 자동증가값

CREATE TABLE SEQ_TEST
(
    IDX     NUMBER(5)       PRIMARY KEY,
    TXT     VARCHAR2(100)   NOT NULL
);

/*
SELECT NVL(MAX(IDX),0) + 1 AS IDX
FROM SEQ_TEST;

INSERT INTO SEQ_TEST VALUES(NVL(MAX(IDX),0) + 1, '안녕하세요');
*/

SELECT TESTSEQ.NEXTVAL FROM DUAL; --한단계씩 증가함
SELECT TESTSEQ.CURRVAL FROM DUAL; --현재값확인

INSERT INTO SEQ_TEST VALUES(TESTSEQ.NEXTVAL,'안녕하세요');
INSERT INTO SEQ_TEST VALUES(TESTSEQ.NEXTVAL,'안녕하세요');
INSERT INTO SEQ_TEST VALUES(TESTSEQ.NEXTVAL,'안녕하세요');

DELETE FROM SEQ_TEST WHERE IDX = 9;

SELECT * FROM SEQ_TEST;

SELECT TESTSEQ2.NEXTVAL FROM DUAL;

--데이터를 적용했으면 무조건 COMMIT를 해주자