SELECT * FROM CUSTOMERS;
SELECT * FROM BUY;

UPDATE CUSTOMERS
SET POINT = 0;

DELETE FROM BUY;

--COMMIT;

--1.물건을 산다. > INSERT BUY > 10% 포인트를 준다
INSERT INTO BUY VALUES('C00001', '새우깡', 1000, 5);
INSERT INTO BUY VALUES('C00001', '젤리', 500, 2);

DELETE FROM BUY
WHERE CID = 'C00001'
;

UPDATE BUY
SET PRICE = 1200
WHERE CID = 'C00001'
;

--AFTER TRIGGER : INSERT문의 데이터가 먼저 추가되고 난 후에 트리거가 동작
--BEFORE TRIGGER : INSERT문의 데이터가 추가 되기 전에 먼저 트리거가 동작을 하고 난 후에 데이터가 추가된다

--3개를 합쳐서 사용할 수 도 있다
/*

CREATE OR REPLACE TRIGGER TRG_BUY_MNGPOINT 
BEFORE DELETE OR INSERT OR UPDATE ON BUY 
REFERENCING OLD AS O NEW AS N 
FOR EACH ROW 
BEGIN

  IF DELETING THEN
    
    UPDATE CUSTOMERS
    SET POINT = POINT - (:O.PRICE * :O.QTY * 0.1)
    WHERE CID = :O.CID
    ;
  
  END IF;
  
  IF UPDATING THEN
  
    UPDATE CUSTOMERS
    SET POINT = POINT + (((:N.PRICE - :O.PRICE) * :N.QTY )* 0.1)
    WHERE CID = :N.CID
    ;
  
  END IF;
  
  IF INSERTING THEN
  
    UPDATE CUSTOMERS
    SET POINT = POINT + (:N.PRICE * :N.QTY * 0.1)
    WHERE CID = :N.CID
    ;
  
  END IF;
  
END;

*/