SELECT T1.MENUID, T2.MENUNAME, T2.MENULVL, 
T1.AUTH_SEL, T1.AUTH_INS, T1.AUTH_UP, T1.AUTH_DEL  
FROM AUTH_MENUS T1, MENUS T2
WHERE T1.MENUID = T2.MENUID
AND T1.AUTHID = 'AUTH001'
AND T2.PARENTID = 'ROOT'
;

SELECT T1.MENUID, T2.MENUNAME, T2.MENULVL,DECODE(T1.AUTH_SEL, 'Y', 'true', 'false') AS AUTH_SEL
FROM AUTH_MENUS T1, MENUS T2
WHERE T1.MENUID = T2.MENUID

;
SELECT T1.MENUID, T1.MENUNAME, T1.MENULVL,
T2.AUTH_SEL, T2.AUTH_UP, T2.AUTH_INS, T2.AUTH_DEL
FROM
(
SELECT *
FROM MENUS
START WITH PARENTID = IN_MENUID
CONNECT BY PRIOR MENUID = PARENTID
) T1, AUTH_MENUS T2
WHERE T1.MENUID = T2.MENUID
AND T2.AUTHID = IN_AUTHID
ORDER BY T1.MENULBL, T1.MENUSEQ
;   
    SELECT *
    FROM
    (
    SELECT MENUID, LPAD(' ', 15*(LEVEL-1)) || MENUNAME AS MENUNAME, MENULVL,PARENTID,
    CONNECT_BY_ROOT MENUID AS ROOTID, -- 최상위값
    CONNECT_BY_ISLEAF --아들이 있으면 0 없으면 1
    FROM MENUS
    START WITH PARENTID = 'ROOT'
    CONNECT BY PRIOR MENUID = PARENTID
    )
    WHERE ROOTID = 'MENU001'
    AND PARENTID != 'ROOT'
    ;