--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESERVATION_GAMES_TBL
--------------------------------------------------------

  CREATE TABLE "RESERVATION_GAMES_TBL" 
  (
  "G_ID" CHAR(4), 
  "G_NAME" VARCHAR2(200), 
  "G_MAKER" CHAR(6), 
  "G_GENRE" CHAR(6),
  "G_R_BEGINDATE" DATE, 
  "G_R_RELEASE" DATE, 
  "G_R_DISCOUNT_PER" NUMBER(2,0) DEFAULT 10,
  "G_R_SUPPLY_PRICE" NUMBER(7,0), 
  "G_R_SALES_PRICE" NUMBER(7,0), 
  "G_R_SHOW" CHAR(1) DEFAULT 'Y'
  );

  ALTER TABLE "RESERVATION_GAMES_TBL" MODIFY ("G_MAKER" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION_GAMES_TBL" ADD CONSTRAINT "RESERVATION_TBL_PK" PRIMARY KEY ("G_ID") USING INDEX  ENABLE;
  ALTER TABLE "RESERVATION_GAMES_TBL" MODIFY ("G_R_SHOW" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION_GAMES_TBL" MODIFY ("G_GENRE" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION_GAMES_TBL" MODIFY ("G_R_BEGINDATE" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION_GAMES_TBL" MODIFY ("G_R_RELEASE" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION_GAMES_TBL" MODIFY ("G_R_DISCOUNT_PER" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION_GAMES_TBL" MODIFY ("G_R_SUPPLY_PRICE" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION_GAMES_TBL" MODIFY ("G_R_SALES_PRICE" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION_GAMES_TBL" MODIFY ("G_ID" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION_GAMES_TBL" MODIFY ("G_NAME" NOT NULL ENABLE);
  

INSERT INTO RESERVATION_GAMES_TBL (G_ID, G_NAME, G_MAKER, G_GENRE, G_R_BEGINDATE, G_R_RELEASE, G_R_DISCOUNT_PER, G_R_SUPPLY_PRICE, G_R_SALES_PRICE, G_R_SHOW) 
VALUES ('G011', 'HUMANKIND', 'CMS011', 'CMS006', to_date('03/17/2021', 'MM/DD/RRRR'), to_date('08/18/2021', 'MM/DD/RRRR'), 10, 20000, 51460, 'Y');

INSERT INTO RESERVATION_GAMES_TBL (G_ID, G_NAME, G_MAKER, G_GENRE, G_R_BEGINDATE, G_R_RELEASE, G_R_DISCOUNT_PER, G_R_SUPPLY_PRICE, G_R_SALES_PRICE, G_R_SHOW) 
VALUES ('G012', 'BIOHAZARD', 'CMS015', 'CMS006', to_date('04/10/2021', 'MM/DD/RRRR'), to_date('05/15/2021', 'MM/DD/RRRR'), 10, 42000, 89000, 'Y');

INSERT INTO RESERVATION_GAMES_TBL (G_ID, G_NAME, G_MAKER, G_GENRE, G_R_BEGINDATE, G_R_RELEASE, G_R_DISCOUNT_PER, G_R_SUPPLY_PRICE, G_R_SALES_PRICE, G_R_SHOW) 
VALUES ('G013', 'PARTY ANIMALS', 'CMS016', 'CMS018', to_date('04/13/2021', 'MM/DD/RRRR'), to_date('07/09/2021', 'MM/DD/RRRR'), 10, 24000, 43000, 'Y');

INSERT INTO RESERVATION_GAMES_TBL (G_ID, G_NAME, G_MAKER, G_GENRE, G_R_BEGINDATE, G_R_RELEASE, G_R_DISCOUNT_PER, G_R_SUPPLY_PRICE, G_R_SALES_PRICE, G_R_SHOW) 
VALUES ('G014', 'BIOMUTANT', 'CMS017', 'CMS006', to_date('04/11/2021', 'MM/DD/RRRR'), to_date('05/26/2021', 'MM/DD/RRRR'), 10, 30000, 64900, 'Y');

INSERT INTO RESERVATION_GAMES_TBL (G_ID, G_NAME, G_MAKER, G_GENRE, G_R_BEGINDATE, G_R_RELEASE, G_R_DISCOUNT_PER, G_R_SUPPLY_PRICE, G_R_SALES_PRICE, G_R_SHOW) 
VALUES ('G015', 'SUCCUBUS', 'CMS019', 'CMS006', to_date('05/06/2021', 'MM/DD/RRRR'), to_date('07/21/2021', 'MM/DD/RRRR'), 10, 19000, 37000, 'Y');

INSERT INTO RESERVATION_GAMES_TBL (G_ID, G_NAME, G_MAKER, G_GENRE, G_R_BEGINDATE, G_R_RELEASE, G_R_DISCOUNT_PER, G_R_SUPPLY_PRICE, G_R_SALES_PRICE, G_R_SHOW) 
VALUES ('G016', 'DUNGEONS, DRAGONS: DARK ALLIANC', 'CMS022', 'CMS010', to_date('04/23/2021', 'MM/DD/RRRR'), to_date('06/23/2021', 'MM/DD/RRRR'), 10, 23000, 50400, 'Y');

INSERT INTO RESERVATION_GAMES_TBL (G_ID, G_NAME, G_MAKER, G_GENRE, G_R_BEGINDATE, G_R_RELEASE, G_R_DISCOUNT_PER, G_R_SUPPLY_PRICE, G_R_SALES_PRICE, G_R_SHOW) 
VALUES ('G017', 'KING''S BOUNTY 2', 'CMS023', 'CMS014', to_date('05/01/2021', 'MM/DD/RRRR'), to_date('08/24/2021', 'MM/DD/RRRR'), 10, 22000, 47800, 'Y');

INSERT INTO RESERVATION_GAMES_TBL (G_ID, G_NAME, G_MAKER, G_GENRE, G_R_BEGINDATE, G_R_RELEASE, G_R_DISCOUNT_PER, G_R_SUPPLY_PRICE, G_R_SALES_PRICE, G_R_SHOW) 
VALUES ('G018', 'SIEGE SURVIVAL: GLORIA VICTIS', 'CMS024', 'CMS010', to_date('04/11/2021', 'MM/DD/RRRR'), to_date('05/18/2021', 'MM/DD/RRRR'), 10, 27000, 42500, 'Y');

INSERT INTO RESERVATION_GAMES_TBL (G_ID, G_NAME, G_MAKER, G_GENRE, G_R_BEGINDATE, G_R_RELEASE, G_R_DISCOUNT_PER, G_R_SUPPLY_PRICE, G_R_SALES_PRICE, G_R_SHOW) 
VALUES ('G019', 'JUST DIE ALREADY', 'CMS025', 'CMS012', to_date('03/15/2021', 'MM/DD/RRRR'), to_date('05/26/2021', 'MM/DD/RRRR'), 10, 6700, 15500, 'Y');

INSERT INTO RESERVATION_GAMES_TBL (G_ID, G_NAME, G_MAKER, G_GENRE, G_R_BEGINDATE, G_R_RELEASE, G_R_DISCOUNT_PER, G_R_SUPPLY_PRICE, G_R_SALES_PRICE, G_R_SHOW) 
VALUES ('G020', 'F1® 2021', 'CMS026', 'CMS013', to_date('05/01/2021', 'MM/DD/RRRR'), to_date('07/17/2021', 'MM/DD/RRRR'), 10, 32000, 66000, 'Y');

  
SELECT * FROM RESERVATION_GAMES_TBL ;
--COMMIT;