CREATE TABLE COMMONS_TBL
(
   CMS_ID           CHAR(6)           PRIMARY KEY,
   CMS_NAME         VARCHAR2(120)     NOT NULL,
   CMS_LVL         NUMBER(3)        NOT NULL,
   CMS_SEQ           NUMBER(5)        NOT NULL,
   PARENT_CMS_ID     CHAR(6)           NULL,
   GROUP_NUM        NUMBER(3)          NOT NULL,
   EXCEPT1        VARCHAR2(100)        NULL, 
   EXCEPT2        VARCHAR2(100)        NULL
);

INSERT INTO COMMONS_TBL VALUES('CMS001', '공통코드', 1 , 1, NULL, 0, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS002', '제조사', 2 , 1, 'CMS001', 1, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS003', '국가', 2 , 2, 'CMS001', 2, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS004', '장르', 2 , 3, 'CMS001', 3, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS005', '한국', 3 , 1, 'CMS003', 2, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS006', 'Action', 3 , 1, 'CMS004', 3, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS007', '미국', 3 , 2, 'CMS003', 2, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS008', '프랑스', 3 , 3, 'CMS003', 2, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS009', '중국', 3 , 4, 'CMS003', 2, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS010', 'Adventure', 3 , 2, 'CMS004', 3, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS011', 'KRAFTON', 3 , 1, 'CMS002', 1, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS012', 'RPG', 3 , 3, 'CMS004', 3, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS013', 'Sports', 3 , 4, 'CMS004', 3, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS014', 'Simulation', 3 , 5, 'CMS004', 3, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS015', 'Creepy Jar', 3 , 2, 'CMS002', 1, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS016', 'Behaviour Interactive Inc', 3 , 3, 'CMS002', 1, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS017', 'Electronic Arts', 3 , 4, 'CMS002', 1, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS018', 'Casual', 3 , 6, 'CMS004', 3, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS019', 'Innersloth', 3 , 5, 'CMS002', 1, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS020', 'UK', 3 , 5, 'CMS003', 2, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS021', '일본', 3 , 6, 'CMS003', 2, NULL, NULL);
--
INSERT INTO COMMONS_TBL VALUES('CMS022', '505 Games', 3 , 6, 'CMS002', 1, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS023', 'Electronic Arts', 3 , 7, 'CMS002', 1, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS024', 'ConcernedApe', 3 , 8, 'CMS002', 1, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS025', 'CAPCOM Co., Ltd.', 3 , 9, 'CMS002', 1, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS026', 'Spike Chunsoft Co., Ltd.', 3 , 10, 'CMS002', 1, NULL, NULL);
--
INSERT INTO COMMONS_TBL VALUES('CMS027', '등급', 2 , 4, 'CMS001', 4, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS028', 'PLATINUM', 3 , 1, 'CMS027', 4, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS029', 'GOLD', 3 , 2, 'CMS027', 4, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS030', 'SILVER', 3 , 3, 'CMS027', 4, NULL, NULL);
INSERT INTO COMMONS_TBL VALUES('CMS031', 'BRONZE', 3 , 4, 'CMS027', 4, NULL, NULL);



SELECT * FROM COMMONS_TBL;
--COMMIT;