CREATE TABLE PAYMENT_TBL
   (   
            PY_ID                        CHAR(5)                   PRIMARY KEY, 
            PY_NAME                 VARCHAR2(30)       NOT NULL, 
            GROUP_NUM           NUMBER(2,0)          NOT NULL, 
            PY_LVL                      NUMBER(2,0)          NOT NULL, 
            PY_SEQ                      NUMBER(2,0)         NOT NULL, 
            PY_DC_PER               NUMBER(3,0)         DEFAULT NULL, 
            PARENT_PY_ID         CHAR(5)
    );
  
INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY001', '지불방식', 1, 1, 2, 0, 'NULL');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY002', '카드', 2, 2, 1, 0, 'PY001');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY003', '현금', 3, 2, 1, 0, 'PY001');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY004', '모바일', 4, 2, 1, 0, 'PY001');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY006', '현대카드', 2, 3, 1, 3, 'PY002');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY007', 'BC카드', 2, 3, 2, 2, 'PY002');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY008', 'SK 알뜰폰', 4, 3, 3, 3, 'PY004');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY009', '신한카드', 2, 3, 3, 6, 'PY002');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY010', 'SK Telecom', 4, 3, 4, 5, 'PY004');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY011', 'LG U+', 4, 3, 2, 2, 'PY004');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY012', 'KT', 4, 3, 1, 2, 'PY004');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY013', 'KB국민카드', 2, 3, 3, 3, 'PY002');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY014', '하나카드', 2, 3, 3, 5, 'PY002');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY015', '롯데카드', 2, 3, 3, 5, 'PY002');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY016', 'NH농협카드', 2, 3, 3, 6, 'PY002');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY017', '삼성카드', 2, 3, 3, 7, 'PY002');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY018', 'LG 알뜰폰', 4, 3, 5, 3, 'PY004');

INSERT INTO PAYMENT_TBL (PY_ID, PY_NAME, GROUP_NUM, PY_LVL, PY_SEQ, PY_DC_PER, PARENT_PY_ID) 
VALUES ('PY019', 'KT 알뜰폰', 4, 3, 6, 3, 'PY004');


SELECT * FROM PAYMENT_TBL ;
--COMMIT;